# Numpy

In [ ]:
# NumPy is a Python library used for working with arrays.
# Has functions for linear algebra, fourier transform, and matrices

In [2]:
import numpy as np

myList = [1,2,3,4,5]
arr = np.array(myList)

arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [10]:
## Multidimensional Array
myList1 = [1,2,3,4,5]
myList2 = [1,3,5,7,9]
myList3 = [2,4,6,8,0]

arr2 = np.array([myList1, myList2, myList3])

arr2

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [11]:
arr2.shape

(3, 5)

In [14]:
arr2.reshape(1, 15)

array([[1, 2, 3, 4, 5, 1, 3, 5, 7, 9, 2, 4, 6, 8, 0]])

In [15]:
arr2.shape

(3, 5)

## Indexing

In [18]:
# Access array element

arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [20]:
arr2[1:,3:]

array([[7, 9],
       [8, 0]])

In [22]:
arr2[0:2, :]

array([[1, 2, 3, 4, 5],
       [1, 3, 5, 7, 9]])

## InBuilt functions

In [8]:
# Generate array for a sequence
arr = np.arange(0,10, 2)
arr

array([0, 2, 4, 6, 8])

In [9]:
# Generate random array within range
arr = np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
# Copy function (array is like ptr)
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr1.copy()
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
## Some Useful condns for EDA
val = 5

print(arr1 < val)
print(arr1[arr1 < val])
print(10*arr1)

[ True  True  True  True False False False False False]
[1 2 3 4]
[10 20 30 40 50 60 70 80 90]


In [35]:
# Identity array
arrId = np.ones(5, dtype=int)
arrId2 = np.ones((2,5), dtype=int)

print(arrId)
print(arrId2)

[1 1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
# Random distribution

arrRandom = np.random.rand(3,3)
arrRandom

array([[0.98609355, 0.96650532, 0.9104144 ],
       [0.696653  , 0.9610457 , 0.25992802],
       [0.18577474, 0.27598279, 0.41766586]])

In [54]:
# Stanadrd Normal Distribution

arrRandNorm = np.random.randn(3,3)
arrRandNorm

array([[-1.56463566,  0.48339016,  1.23168403],
       [-2.33324544,  0.43370733,  0.22002154],
       [-0.15778283, -1.20987918, -0.972421  ]])

In [64]:
# Random integers

arrRandInt = np.random.randint(0,10,10)
arrRandInt

array([4, 7, 6, 2, 8, 5, 4, 5, 1, 4])

In [70]:
# Random Sample

arrRandSample = np.random.random_sample((1,5))
arrRandSample

array([[0.12721483, 0.886221  , 0.48891919, 0.35759602, 0.48915173]])